name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    env:
      TEST_BASE_URL: http://localhost:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./lab2.sln

      - name: Build solution
        run: dotnet build ./lab2.sln --no-restore

      - name: Create .env for Docker Compose
        run: |
          cat > ./lab2/.env <<EOF
          DB_HOST=db
          DB_PORT=5432
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          EOF

      - name: Start containers
        working-directory: ./lab2
        run: docker compose up --build -d

      - name: Wait for API health
        run: |
          for i in {1..30}; do
            if curl -fsS http://localhost:8080/health; then
              exit 0
            fi
            sleep 5
          done
          echo "API did not become healthy in time"
          docker ps
          exit 1
      - name: Show repo structure
        run: find . -name "*.csproj"
      - name: Run functional tests
        env:
          TEST_BASE_URL: http://localhost:8080
        run: dotnet test ./lab2.Tests/lab2.Tests/lab2.Tests.csproj --no-build --verbosity normal

      - name: Show container logs on failure
        if: failure()
        working-directory: ./lab2
        run: docker compose logs

      - name: Stop containers
        if: always()
        working-directory: ./lab2
        run: docker compose down -v
